from .dtos import (
    AnalisisEstructuralBase,
    AnalisisEstructuralCreate,
    AnalisisEstructuralRead,
    CasoInspeccionBase,
    CasoInspeccionCreate,
    CasoInspeccionRead,
    CatalogoElementoBase,
    CatalogoElementoCreate,
    CatalogoElementoRead,
    DeteccionAutomaticaBase,
    DeteccionAutomaticaCreate,
    DeteccionAutomaticaRead,
    ModeloIABase,
    ModeloIACreate,
    ModeloIARead,
    PlantillaPromptBase,
    PlantillaPromptCreate,
    PlantillaPromptRead,
    ReporteAnalisisBase,
    ReporteAnalisisCreate,
    ReporteAnalisisRead,
    SeleccionElementoBase,
    SeleccionElementoCreate,
    SeleccionElementoRead,
)

